const fs = require("node:fs");

function writeJSON(filePath, value) {
  fs.writeFileSync(filePath, JSON.stringify(value));
}

function writeWikiSeed(filePath, sourceURL, pages) {
  const generated = `// Generated by scripts/import-wiki.cjs from ${sourceURL}\nwindow.WIKI_SEED = ${JSON.stringify(pages, null, 2)};\n`;
  fs.writeFileSync(filePath, generated, "utf8");
}

module.exports = { writeJSON, writeWikiSeed };
